name: GitHub Pages
permissions:
  contents: read

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Set up Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install asv
        run: pip3 install asv

      - name: Build
        run: asv publish

      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./html
